var searchData=
[
  ['accountcontroller',['AccountController',['../class_alfa_accounting_1_1_controllers_1_1_account_controller.html',1,'AlfaAccounting.Controllers.AccountController'],['../class_alfa_accounting_1_1_controllers_1_1_account_controller.html#a31bb8afad3df5a35af60d598886942d2',1,'AlfaAccounting.Controllers.AccountController.AccountController()'],['../class_alfa_accounting_1_1_controllers_1_1_account_controller.html#adff8966cf2dd3222d2198cce217cedd5',1,'AlfaAccounting.Controllers.AccountController.AccountController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)']]],
  ['addbooking',['AddBooking',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a5c17315b4daf73640327bfefa8b34ad7',1,'AlfaAccounting.Controllers.BookingViewModelsController.AddBooking()'],['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a26b7e355b83aa0974f8b3a42c3096924',1,'AlfaAccounting.Controllers.BookingViewModelsController.AddBooking(AddBookingViewModel model)']]],
  ['addcommentcreate',['AddCommentCreate',['../class_alfa_accounting_1_1_controllers_1_1_blog_view_models_controller.html#a147f8c8c66c4416e2bfca81afc48430c',1,'AlfaAccounting.Controllers.BlogViewModelsController.AddCommentCreate()'],['../class_alfa_accounting_1_1_controllers_1_1_blog_view_models_controller.html#a9a48c7e353962802d1d3b1b8c8a0d315',1,'AlfaAccounting.Controllers.BlogViewModelsController.AddCommentCreate([Bind(Include=&quot;CommentId, CommentedDate, CommentTitle, CommentBody, BlogId, Id&quot;)] Comment comment)']]],
  ['addpaymenthistory',['AddPaymentHistory',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a5d73d599f1b0a2ef694e4fe462df8a21',1,'AlfaAccounting.Controllers.BookingViewModelsController.AddPaymentHistory(int? id)'],['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a2dd3ff554a0b0a99340572129dc87035',1,'AlfaAccounting.Controllers.BookingViewModelsController.AddPaymentHistory([Bind(Include=&quot;PaymentHistoryId,PaymentDateTime,PaymentType,CreditAmount,DebitAmount,TransactionId,PaymentId,InvoiceId,Id&quot;)] PaymentHistory paymentHistory)']]],
  ['addrole',['AddRole',['../class_alfa_accounting_1_1_controllers_1_1_admin_controller.html#a59853ef1d5370e88b096ff325cd1ff6f',1,'AlfaAccounting.Controllers.AdminController.AddRole()'],['../class_alfa_accounting_1_1_controllers_1_1_admin_controller.html#a3d687320b749a1965076591cac812ef4',1,'AlfaAccounting.Controllers.AdminController.AddRole(RoleDTO paramRoleDTO)']]],
  ['addtocart',['AddToCart',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a741b6cc23c814a19db514ad186687986',1,'AlfaAccounting::Controllers::BookingViewModelsController']]],
  ['adminbooking',['AdminBooking',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#adf4a14a9683e52f9dff922c5e58bc125',1,'AlfaAccounting::Controllers::BookingViewModelsController']]],
  ['admincontroller',['AdminController',['../class_alfa_accounting_1_1_controllers_1_1_admin_controller.html',1,'AlfaAccounting::Controllers']]],
  ['alfaaccounting',['AlfaAccounting',['../namespace_alfa_accounting.html',1,'']]],
  ['amendbookdates',['AmendBookDates',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a0e2390ab528b31f0e6f08cb2e1e3b4d6',1,'AlfaAccounting.Controllers.BookingViewModelsController.AmendBookDates(int? id)'],['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#ac7f71cbbf29ebdd1103368248f4f70f8',1,'AlfaAccounting.Controllers.BookingViewModelsController.AmendBookDates([Bind(Include=&quot;BookingId,BookedDate,BookingStartDateTime,BookingEndDateTime,UnitPriceId,Id,InvoiceId&quot;)] AmendBookDatesDateFilterModel model)']]],
  ['amendbookingconfirmation',['AmendBookingConfirmation',['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#afb2e1c7475bb061d45f7a810f5420d75',1,'AlfaAccounting.Controllers.BookingViewModelsController.AmendBookingConfirmation()'],['../class_alfa_accounting_1_1_controllers_1_1_booking_view_models_controller.html#a6e5358b2fd882c060e26353c85658d87',1,'AlfaAccounting.Controllers.BookingViewModelsController.AmendBookingConfirmation(bool answer)']]],
  ['controllers',['Controllers',['../namespace_alfa_accounting_1_1_controllers.html',1,'AlfaAccounting']]]
];
